[package]
name = "todo-cras"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
termcolor = "1.1"
chrono = "0.4"
fastrand = "1.5.0"
read_input = "0.8"
termion = "1.5.6"
